import React from "react";
import Head from "next/head";
import Home from "@/routes/home";

const HomePage: React.FC = () => {
  return (
    <>
      <Head>
        <title>File sharing API server </title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='max-w-2xl mx-auto sm:py-4 sm:px-6 lg:max-w-7xl lg:py-16 lg:px-8'>
        <Home />
      </main>
    </>
  );
};

export default HomePage;
